### ISSUE TITLE
!! HELP WANTED !! Many errors while building using Visual Studio 2019. [SOLVED]

### ISSUE THREAD

**Issue by Se7enSlasher** [Se7enSlasher/The-Improved-and-Modified-Version-of-BeatDrop-Music-Visualizer#1]
I just tried to compile this code, but it has more errors in it. Can anyone should fix this?
![image](https://user-images.githubusercontent.com/74858188/189349967-e1d77f02-8806-407b-be0f-61709f57878c.png)

**Comment by erraata** [comment]
Check this commit: [https://github.com/WACUP/vis_milk2/commit/44b685a70682e649ba8b5ae81d15faecb4b0156c](url) for the nseel-compiler.c errors. I was getting similar error messages while trying to compile BeatDrop2077 and was able to get it to build when I replaced nseel-compiler.c with WACUP's version.

I don't normally work with Visual Studio or C++ so I'm not sure about the others. Take a look at https://github.com/milkdrop2077/BeatDrop2077[](url) and compare their plugin.cpp is my suggestion.

**Comment by Se7enSlasher** [comment]
It built succesfully, but idk why the _Pnext was 0x4.
![image](https://user-images.githubusercontent.com/74858188/189531068-ca8bfbbb-ed20-4916-91e3-302fa7b5fbbb.png)

**Comment by Se7enSlasher** [comment]
Aight. I am gonna close this issue because it's solved. @milkdrop2077 gave me a generated .exe file and I should give a huge thanks.

**Comment by OfficialIncubo** [comment]
Forgot to change from "Debug" to "Release". So I managed to compile the .exe file.
